#---------注册中心------------#

## 高可用注册中心，dev、test环境启动工程即集群注册中心
## maven隔离
spring:
  profiles:
    active: @activatedProperties@
  application:
    name: server-center
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    uri-encoding: UTF-8



